### ISSUE TITLE
Support new Loki chart versions - Change to Values file

### ISSUE THREAD

**Issue by zfalen-deloitte** [andreswebs/terraform-aws-eks-monitoring#3]
```
level=error ts=2023-05-19T17:31:52.700290762Z caller=main.go:56 msg="validating config" err="invalid queryrange config: the yaml flag `split_queries_by_interval` must now be set in the `limits_config` section instead of the `query_range` config section"
```

Running on EKS 1.25.

When omitting the `chart_version_loki_distributed` variable, the module installs `latest` version of the `loki-distributed` helm chart by default, triggering the error above. 

Working backwards all the way to `0.51.2`, I was never actually able to get this working by specifying `chart_version_loki_distributed`. Prior to `0.51.2` a different config error is reported; this release is almost 1yr old. Not sure if this module is working on other cluster versions - but clearly has not for the `distributed` loki in some time. 

Noted also that setting `loki_mode = "single"` does _not_ deploy the standard `loki` chart - still deploys `loki-distributed` contrary to provided docs _(and apparently also to the `count` setting in the `main.tf` file for `resource "helm_release" "loki" { ... }`)_

Will need to modify the `modules/resources/helm-values/loki-distributed.yml.tftpl` values file to move the `split_queries_by_interval` at this line https://github.com/andreswebs/terraform-aws-eks-monitoring/blob/4947b337aa7edb8d96630742f2951c794cbeb105/modules/resources/helm-values/loki-distributed.yml.tftpl#L88

... into this block: https://github.com/andreswebs/terraform-aws-eks-monitoring/blob/4947b337aa7edb8d96630742f2951c794cbeb105/modules/resources/helm-values/loki-distributed.yml.tftpl#L73

**Comment by zfalen-deloitte** [comment]
**Update:**

I was able to resolve Loki errors by forking and modifying the values file. 

_Changes:_
to support permissions for WAL, set WAL to write to the volume mounted at `/var/loki/` .... added to `Values.loki.ingester`: 

```
      wal:
        dir: "/var/loki/wal"
```

Moved `split_queries_by_interval` to `values.loki.limits_config`.

Fork link:
https://github.com/zfalen-deloitte/terraform-aws-eks-monitoring/blob/main/modules/resources/helm-values/loki-distributed.yml.tftpl

**Comment by andreswebs** [comment]
Thanks! 
I didn't have the bandwidth to maintain this, but glad to know you were able to work it out.
